name: Fatal Frame 1 (US)
sha1: 5ac4626e0d76218e977b01f4fae5948de9a1755e
options:
    basename: SLUS_203.88
    target_path: SLUS_203.88
    base_path: .
    asm_path: asm
    src_path: ../../src
    build_path: build
    asset_path: assets
    compiler: EEGCC
    find_file_boundaries: False
    platform: ps2
    string_encoding: EUC-JP
    create_undefined_funcs_auto: False
    create_undefined_syms_auto: True
    undefined_funcs_auto_path: undefined_funcs_auto.txt
    undefined_syms_auto_path: undefined_syms_auto.txt
    symbol_addrs_path: symbol_addrs.txt
    extensions_path: ../../tools/splat_ext
    section_order: [".text", ".vutext", ".data", ".vudata", ".rodata", ".lit4", ".sdata", ".sbss", ".bss", ".vubss"]
    auto_all_sections: [".data", ".sdata", ".sbss", ".lit4", ".rodata", ".bss"]
    disasm_unknown: True
    subalign: 4
    named_regs_for_c_funcs: False
    gp_value: 0x35d070
# custom field used by fix_linkerscript.py to fix linkerscript alignments
_section_subalign:
    elf_header: 8
    main: 2
    main_bss: 1
    reg_info: 4
    mips_debug: 4
    rest: 4
segments:
    - [0, databin, elf_header]
    - name: main
      type: code
      start: 0x1000
      vram: 0x100000
      bss_size: 0x0b2c30
      align: 1
      subalign: 2 # safe subalign value. proper values are applied by fix_linkerscript.py where necessary
      # text has align 8 but other sections may have a different alignment ...
      # explicit align correction is performed by fix_linkerscript.py during
      # project configuration. vram address is used, when reported, in non text
      # sections to calculate the correct align value.
      subsegments:
          - [0x1000,   asm, crt0]
          - [0x10c8,   c,   main/main]
          - [0x1380,   c,   outgame/mode_slct]
          - [0x4b30,   c,   outgame/memory_album]
          - [0xbf68,   c,   main/gamemain]
          - [0xc2f8,   c,   main/glob]
          - [0xc2f8,   c,   os/system]
          - [0xc938,   c,   os/fileload]
          - [0xcaa0,   c,   os/key_cnf]
          - [0xcc48,   c,   os/backup]
          - [0xcee0,   c,   os/pad]
          - [0xda68,   c,   os/eeiop/eeiop]
          - [0xde20,   c,   os/eeiop/cdvd/eecdvd]
          - [0xe308,   c,   os/eeiop/adpcm/ea_ctrl]
          - [0xeec8,   c,   os/eeiop/adpcm/ea_cmd]
          - [0xf308,   c,   os/eeiop/adpcm/ea_dat]
          - [0xf358,   c,   os/eeiop/adpcm/ea_btlmode]
          - [0xf658,   c,   os/eeiop/adpcm/ea_gameover]
          - [0xf860,   c,   os/eeiop/adpcm/ea_scene]
          - [0xfb10,   c,   os/eeiop/adpcm/ea_magatoki]
          - [0xfe40,   c,   os/eeiop/adpcm/ea_shinkan]
          - [0x10178,  c,   os/eeiop/adpcm/ea_puzzle]
          - [0x10478,  c,   os/eeiop/adpcm/ea_soul]
          - [0x10740,  c,   os/eeiop/adpcm/ea_tape]
          - [0x10948,  c,   os/eeiop/adpcm/ea_gdead]
          - [0x10b78,  c,   os/eeiop/adpcm/ea_event]
          - [0x10f98,  c,   os/eeiop/adpcm/ea_ghost]
          - [0x11400,  asm, os/eeiop/adpcm/ea_autog]
          - [0x11958,  asm, os/eeiop/adpcm/ea_hiso]
          - [0x11d18,  asm, os/eeiop/adpcm/ea_furn]
          - [0x12218,  asm, os/eeiop/adpcm/ea_map]
          - [0x12460,  asm, os/eeiop/eese]
          - [0x14108,  asm, os/eeiop/se_cmd]
          - [0x14788,  asm, os/eeiop/se_data]
          - [0x14c88,  asm, os/eeiop/se_ev]
          - [0x14fe8,  asm, os/eeiop/se_trans]
          - [0x15420,  asm, os/eeiop/se_door]
          - [0x15958,  asm, os/eeiop/se_foot]
          - [0x15e10,  asm, os/eeiop/se_event]
          - [0x16150,  asm, os/eeiop/se_srund]
          - [0x16490,  asm, os/eeiop/sd_room]
          - [0x16680,  asm, os/eeiop/se_plyr]
          - [0x16cd0,  asm, common/ul_math]
          - [0x16fc8,  asm, common/utility]
          - [0x17028,  asm, graphics/graph2d/compress]
          - [0x18a08,  asm, graphics/graph2d/effect]
          - [0x1b160,  asm, graphics/graph2d/effect_sub]
          - [0x21398,  asm, graphics/graph2d/effect_sub2]
          - [0x28e40,  asm, graphics/graph2d/effect_scr]
          - [0x32a70,  asm, graphics/graph2d/effect_obj]
          - [0x37430,  asm, graphics/graph2d/effect_oth]
          - [0x47330,  asm, graphics/graph2d/effect_rdr]
          - [0x48ab8,  asm, graphics/graph2d/effect_ene]
          - [0x53ed0,  asm, graphics/graph2d/g2d_debug]
          - [0x55db8,  asm, graphics/graph2d/g2d_main]
          - [0x56048,  asm, graphics/graph2d/message]
          - [0x5a8a8,  asm, graphics/graph2d/number]
          - [0x5ac98,  asm, graphics/graph2d/snapshot]
          - [0x5af10,  asm, graphics/graph2d/tim2]
          - [0x5eb40,  asm, graphics/graph2d/tim2_new]
          - [0x5fd58,  asm, graphics/graph2d/rare_ene]
          - [0x60b88,  asm, graphics/graph3d/gra3d]
          - [0x65240,  asm, graphics/graph3d/leditor]
          - [0x66580,  asm, graphics/graph3d/load3d]
          - [0x676b0,  asm, graphics/motion/mdlwork]
          - [0x68d88,  asm, graphics/motion/mdlact]
          - [0x69cc0,  asm, graphics/motion/mime]
          - [0x6b7c8,  asm, graphics/motion/accessory]
          - [0x6f4e0,  asm, graphics/motion/motion]
          - [0x72508,  asm, graphics/motion/anicode]
          - [0x72dc0,  asm, graphics/graph3d/object]
          - [0x72df8,  asm, graphics/graph3d/sce_pp3]
          - [0x73050,  asm, graphics/graph3d/sgsgd]
          - [0x739e8,  asm, graphics/graph3d/sglib]
          - [0x747f0,  asm, graphics/graph3d/sgsu]
          - [0x75f60,  asm, graphics/graph3d/sgdma]
          - [0x76aa0,  asm, graphics/graph3d/sglight]
          - [0x79c48,  asm, graphics/graph3d/sgsup]
          - [0x7a9c8,  asm, graphics/graph3d/sgcam]
          - [0x7ba68,  asm, graphics/graph3d/shadow]
          - [0x7e4d8,  asm, graphics/graph3d/mirror]
          - [0x7fcc8,  asm, graphics/mov/movie]
          - [0x83f30,  asm, graphics/scene/fod]
          - [0x85960,  asm, graphics/scene/scene]
          - [0x88800,  asm, ingame/ingame]
          - [0x89578,  asm, ingame/ig_init]
          - [0x89ae0,  asm, ingame/camera/camera]
          - [0x8e618,  asm, ingame/enemy/ene_ctl]
          - [0x91ea8,  asm, ingame/enemy/move_ctl]
          - [0x99728,  asm, ingame/entry/entry]
          - [0x99910,  asm, ingame/plyr/time_ctl]
          - [0x99cc0,  asm, ingame/entry/ap_bgost]
          - [0x99fd8,  asm, ingame/entry/ap_dgost]
          - [0x9a4e8,  asm, ingame/entry/ap_fgost]
          - [0x9b190,  asm, ingame/entry/ap_ggost]
          - [0x9b880,  asm, ingame/entry/ap_pgost]
          - [0x9be50,  asm, ingame/entry/ap_rgost]
          - [0x9cd50,  asm, ingame/entry/ap_sgost]
          - [0x9dc18,  asm, ingame/entry/ap_zgost]
          - [0x9e508,  asm, ingame/event/ev_main]
          - [0xa07c0,  asm, ingame/event/ev_spcl]
          - [0xb1cf0,  asm, ingame/event/ev_load]
          - [0xb30f0,  asm, ingame/event/mv_cmnd]
          - [0xb3250,  asm, ingame/info/inf_disp]
          - [0xbaa00,  asm, ingame/map/map_ctrl]
          - [0xbe398,  asm, ingame/map/map_area]
          - [0xbece0,  asm, ingame/map/door_ctl]
          - [0xc66d0,  asm, ingame/map/doortype]
          - [0xc67f8,  asm, ingame/map/rotd_ctl]
          - [0xc6d60,  asm, ingame/map/find_ctl]
          - [0xc7118,  asm, ingame/map/furn_ctl]
          - [0xc8b98,  asm, ingame/map/furn_dat]
          - [0xc8bb8,  asm, ingame/map/furn_eff]
          - [0xc9148,  asm, ingame/map/item_ctl]
          - [0xc9ca8,  asm, ingame/map/map_htck]
          - [0xca958,  asm, ingame/map/furn_spe/furn_spe]
          - [0xce500,  asm, ingame/map/furn_spe/fsla_main]
          - [0xcece8,  asm, ingame/map/furn_spe/fspe_acs]
          - [0xced88,  asm, ingame/map/furn_spe/adj_valg]
          - [0xcf0a0,  asm, ingame/menu/item]
          - [0xd4a28,  asm, ingame/menu/gameover]
          - [0xd5070,  asm, ingame/menu/pause]
          - [0xd5a10,  asm, ingame/menu/ig_album]
          - [0xdd1e8,  asm, ingame/menu/ig_camra]
          - [0xe0cd0,  asm, ingame/menu/ig_menu]
          - [0xe5538,  asm, ingame/menu/ig_spd_menu]
          - [0xe5de0,  asm, ingame/menu/item_get]
          - [0xe78b8,  asm, ingame/menu/ig_file]
          - [0xee668,  asm, ingame/menu/ig_rank]
          - [0xf1970,  asm, ingame/menu/ig_glst]
          - [0xf3d78,  asm, ingame/menu/ig_map]
          - [0xf7268,  asm, ingame/menu/ig_option]
          - [0xfa1c8,  asm, ingame/menu/sp_menu]
          - [0x100458, asm, ingame/map/door_conte]
          - [0x100838, asm, ingame/photo/photo]
          - [0x1012b8, asm, ingame/photo/pht_main]
          - [0x101af0, asm, ingame/photo/pht_make]
          - [0x1059a8, asm, ingame/plyr/plyr_ctl]
          - [0x10e5b0, asm, ingame/plyr/unit_ctl]
          - [0x10ed38, asm, edit/test_2d]
          - [0x10ef08, asm, outgame/scn_test]
          - [0x113ca8, asm, outgame/title]
          - [0x116dd0, asm, graphics/graph2d/takep_pe]
          - [0x117b58, asm, mc/mc_main]
          - [0x119b60, asm, mc/mc_acs]
          - [0x11a4b8, asm, mc/mc_album]
          - [0x11b000, asm, mc/mc_exec]
          - [0x11c3d0, asm, mc/mc_start]
          - [0x11c998, asm, mc/mc_disp]
          - [0x11caa8, asm, mc/mc_at]
          - [0x11d260, asm, outgame/outgame]
          - [0x11d988, asm, outgame/btl_mode/btl_menu]
          - [0x11ed08, asm, outgame/btl_mode/btl_mode]
          - [0x11f5d0, asm, ingame/event/wan_soul]
          - [0x121030, asm, ingame/event/wan_dat]
          - [0x121098, asm, outgame/sound_test]
          - [0x1225c0, textbin, text_rest]
          - [0x1475b0, textbin, vutext]
          # ######################## DATA    (vram: 0x250180) ##################################
          - { start: 0x151180, type: .data,   vram: 0x250180, name: outgame/mode_slct          }
          - { start: 0x152ae0, type: .data,   vram: 0x251ae0, name: outgame/memory_album       }
          - { start: 0x1532c0, type: .data,   vram: 0x2522c0, name: main/glob                  }
          - { start: 0x166eb0, type: .data,   vram: 0x265eb0, name: os/system                  }
          - { start: 0x1670e0, type: .data,   vram: 0x2660e0, name: os/key_cnf                 }
          - { start: 0x167200, type: .data,   vram: 0x266200, name: os/pad                     }
          - { start: 0x167240, type: .data,   vram: 0x266240, name: os/eeiop/eeiop             }
          - { start: 0x167800, type: .data,   vram: 0x266800, name: os/eeiop/adpcm/ea_ctrl     }
          - { start: 0x167c40, type: .data,   vram: 0x266c40, name: os/eeiop/adpcm/ea_dat      }
          - { start: 0x1687c0, type: data,    vram: 0x2677c0, name: data_10                    }
          # ######################## VUDATA  (vram: 0x349608) ##################################
          - [0x24a608, databin, vudata]
          # ######################## RODATA  (vram: 0x349680) ##################################
          - { start: 0x24a680, type: .rodata, vram: 0x349680, name: outgame/mode_slct          }
          - { start: 0x24a7e0, type: .rodata, vram: 0x3497e0, name: outgame/memory_album       }
          - { start: 0x24a8b0, type: .rodata, vram: 0x3498b0, name: main/gamemain              }
          - { start: 0x24a8d0, type: .rodata, vram: 0x3498d0, name: os/system                  }
          - { start: 0x24a990, type: .rodata, vram: 0x349990, name: os/backup                  }
          - { start: 0x24a9b0, type: .rodata, vram: 0x3499b0, name: os/pad                     }
          - { start: 0x24a9c0, type: .rodata, vram: 0x3499c0, name: os/eeiop/eeiop             }
          - { start: 0x24a9f0, type: .rodata, vram: 0x3499f0, name: os/eeiop/adpcm/ea_ctrl     }
          - { start: 0x24aa30, type: .rodata, vram: 0x349a30, name: os/eeiop/adpcm/ea_btlmode  }
          - { start: 0x24aa50, type: .rodata, vram: 0x349a50, name: os/eeiop/adpcm/ea_scene    }
          - { start: 0x24aa70, type: .rodata, vram: 0x349a70, name: os/eeiop/adpcm/ea_magatoki }
          - { start: 0x24aa90, type: .rodata, vram: 0x349a90, name: os/eeiop/adpcm/ea_shinkan  }
          - { start: 0x24aab0, type: .rodata, vram: 0x349ab0, name: os/eeiop/adpcm/ea_puzzle   }
          - { start: 0x24aad0, type: .rodata, vram: 0x349ad0, name: os/eeiop/adpcm/ea_soul     }
          - { start: 0x24aaf0, type: .rodata, vram: 0x349af0, name: os/eeiop/adpcm/ea_tape     }
          - { start: 0x24ab10, type: .rodata, vram: 0x349b10, name: os/eeiop/adpcm/ea_gdead    }
          - { start: 0x24ab30, type: .rodata, vram: 0x349b30, name: os/eeiop/adpcm/ea_event    }
          - { start: 0x24abc0, type: .rodata, vram: 0x349bc0, name: os/eeiop/adpcm/ea_ghost    }
          - { start: 0x24abe0, type: rodata,  vram: 0x349be0, name: rodata_19                  }
          # ######################## LIT4    (vram: 0x355080) ##################################
          - { start: 0x256080, type: .lit4,   vram: 0x355080, name: outgame/mode_slct          }
          - { start: 0x256088, type: .lit4,   vram: 0x355088, name: outgame/memory_album       }
          - { start: 0x256120, type: .lit4,   vram: 0x355120, name: os/pad                     }
          - { start: 0x25612c, type: .lit4,   vram: 0x35512c, name: os/eeiop/adpcm/ea_cmd      }
          - { start: 0x256144, type: lit4,    vram: 0x355144, name: lit4_5                     }
          # ######################## SDATA   (vram: 0x356300) ##################################
          - { start: 0x257300, type: .sdata,  vram: 0x356300, name: outgame/mode_slct          }
          - { start: 0x25731a, type: .sdata,  vram: 0x35631a, name: outgame/memory_album       }
          - { start: 0x25731c, type: .sdata,  vram: 0x35631c, name: main/gamemain              }
          - { start: 0x257328, type: .sdata,  vram: 0x356328, name: main/glob                  }
          - { start: 0x257338, type: .sdata,  vram: 0x356338, name: os/system                  }
          - { start: 0x257350, type: .sdata,  vram: 0x356350, name: os/eeiop/adpcm/ea_ghost    }
          - { start: 0x257354, type: sdata,   vram: 0x356354, name: sdata_7                    }
          # ######################## SBSS    (vram: 0x357880) ##################################
          - { start: 0x258880, type: .sbss,   vram: 0x357880, name: outgame/mode_slct          }
          - { start: 0x258880, type: .sbss,   vram: 0x357888, name: outgame/memory_album       }
          - { start: 0x258880, type: .sbss,   vram: 0x357894, name: os/system                  }
          - { start: 0x258880, type: .sbss,   vram: 0x357898, name: os/eeiop/cdvd/eecdvd       }
          - { start: 0x258880, type: .sbss,   vram: 0x35789b, name: os/eeiop/adpcm/ea_ctrl     }
          - { start: 0x258880, type: .sbss,   vram: 0x35789c, name: os/eeiop/adpcm/ea_ghost    }
          - { start: 0x258880, type: sbss,    vram: 0x3578a0, name: sbss_7                     }
          # ######################## BSS     (vram: 0x357c80) ##################################
          - { start: 0x25888c, type: bss,     vram: 0x357c80, name: bss_1                      }
          - { start: 0x25888c, type: .bss,    vram: 0x357dc8, name: outgame/mode_slct          }
          - { start: 0x25888c, type: .bss,    vram: 0x357df0, name: outgame/memory_album       }
          - { start: 0x25888c, type: .bss,    vram: 0x357e40, name: os/fileload                }
          - { start: 0x25888c, type: .bss,    vram: 0x357ea8, name: os/eeiop/cdvd/eecdvd       }
          - { start: 0x25888c, type: bss,     vram: 0x357ed0, name: bss_6                      }
          # ######################## VUBSS   (vram: 0x40a8b0) ##################################
          - { start: 0x25888c, type: bss,     vram: 0x40a8b0, name: vubss_1                    }
    - [0x258880, databin, reg_info]
    - [0x2588a4, databin, mips_debug]
    - [0x71d5d4, databin, rest]
    - [0x7775b8]

# Section Headers:
#   [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
#   [ 0]                   NULL            00000000 000000 000000 00      0   0  0
#   [ 1] .text             PROGBITS        00100000 001000 1465a4 00  AX  0   0 64
#   [ 2] .vutext           PROGBITS        002465b0 1475b0 009b80 00  AX  0   0 16
#   [ 3] .reginfo          MIPS_REGINFO    00250130 25888c 000018 01      0   0  4
#   [ 4] .data             PROGBITS        00250180 151180 0f9488 00  WA  0   0 64
#   [ 5] .vudata           PROGBITS        00349608 24a608 000000 00  WA  0   0  1
#   [ 6] .rodata           PROGBITS        00349680 24a680 00b9a8 00   A  0   0 16
#   [ 7] .lit4             PROGBITS        00355080 256080 001268 00 WAp  0   0  4
#   [ 8] .sdata            PROGBITS        00356300 257300 001534 00 WAp  0   0  8
#   [ 9] .sbss             NOBITS          00357880 258880 0003f4 00 WAp  0   0  8
#   [10] .bss              NOBITS          00357c80 25888c 0b2c30 00  WA  0   0 64
#   [11] .vubss            NOBITS          0040a8b0 25888c 000000 00  WA  0   0  1
#   [12] .mdebug           MIPS_DEBUG      0040a8b0 2588a4 4c4d30 01      0   0  4
